extends:
  file: ../pipeline.yaml
agent:
  image: denispalnitskyaurea/python-builder-sonar
pipelines:
  pullRequest:
    build:
      steps:                  
      - sh:  pytest --junitxml=pytest-report.xml
        name: python-unit-test
      - sh: sonar-scanner
        name: run-sonnar-scanner
  release:
    setVersion:
      steps:
      - sh: echo \$(jx-release-version) > VERSION
        name: next-version
        comment: so we can retrieve the version in later steps
      # TODO set the version in source?
      - sh: jx step tag --version \$(cat VERSION) 
        name: tag-version

    build:
      steps:                  
      - sh:  pytest
        name: python-unit-test
      # - sh: coverage run --branch
      #  name: run-coverage
      #- sh: coverage xml -i
      #  name: output-coverage
      - sh: sonar-scanner -Dsonar.python.xunit.reportPath=pytest-report.xml
        name: run-sonnar-scanner 